config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  resources :cats do
    # /cats/:cat_id/toys/:toy_id
    resources :toys, only: [:index, :new]
  end

  # /toys/:toy_id
  resources :toys, only: [:show, :create, :update, :destroy]

  root to: redirect('/cats')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :name, :skill, presence: true
  has_many :toys
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  TOYTYPES = [
    'string',
    'yarnball',
    'mouse'
  ]

  validates :name, :cat_id, :toytype, presence: true
  validates :toytype, inclusion: TOYTYPES

  belongs_to :cat
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    # GET /cats
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    # GET /cats/new
    @cat = Cat.new
    render :new
  end

  def create
    # POST /cats
    # { "cat": { "name": "Sally" } }
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      # render json: @cat.errors.full_messages, status: :unprocessable_entity
      render :new
    end
  end

  def edit
    # GET /cats/:id/edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    cat = Cat.find(params[:id])
    cat.destroy

    redirect_to cats_url
  end

  private

    def cat_params
      params[:cat].permit(:name, :skill)
    end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    # /cats/:cat_id:/toys
    cat = Cat.find(params[:cat_id])
    render json: cat.toys
  end

  def show
    # /cats/:cat_id/toys/:id
    render json: Toy.find(params[:id])
  end

  def new
    # GET /cats/:cat_id/toys/new
    @toy = Toy.new
    @cat = Cat.find(params[:cat_id])
    render :new
  end

  def create
    # POST /toys
    @toy = Toy.new(toy_params)
    @cat = @toy.cat # or Cat.find(params[:toy][:cat_id])

    if @toy.save
      redirect_to cat_url(@cat)
    else
      render :new
      # raise "ToyError!"
      # render json: toy.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    toy = Toy.find(params[:id])
    toy.destroy
    render json: toy
  end

  def edit

  end

  def update
    toy = Toy.find(params[:id])
    if toy.update(toy_params)
      render json: toy
    else
      render json: toy.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

    def toy_params
      params[:toy].permit(:cat_id, :name, :toytype)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    render json: @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
    render json: @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% form_method = cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = cat.persisted? ? "Update Cat!" : "Create Cat!" %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>" />

  <label for="cat_name">Name:</label>
  <input type="text"
         name="cat[name]"
         id="cat_name"
         value="<%= cat.name %>" />

  <label for="cat_skill">Skill:</label>
  <input type="text"
         name="cat[skill]"
         id="cat_skill"
         value="<%= cat.skill %>" />

  <button type="submit" style="display:block;"><%= submit_text %></button>
</form>

app/views/cats/edit.html.erb
<h1>Update <%= @cat.name %>!</h1>

<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>index</title>
    <meta charset="utf-8" />
  </head>
  <body>
    <h1>All the Cats</h1>
    <ul>
      <% @cats.each do |cat| %>
      <li>
        <a href="<%= cat_url(cat) %>"><%= cat.name %></a>
        <form action="<%= cat_url(cat) %>" method="post">
          <input type="hidden" name="_method" value="delete" />
          <button type="submit">Destroy Cat!</button>
        </form>
      </li>
      <% end %>
    </ul>
    <a href="<%= new_cat_url %>">New Cat</a>
  </body>
</html>

app/views/cats/new.html.erb
<h1>Make A New Cat!</h1>

<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<pre><%= @cat.to_json %></pre>

<ul>
  <% @cat.toys.each do |toy| %>
  <li><%= toy.name %></li>
  <% end %>
</ul>

<ul>
  <li><a href="<%= new_cat_toy_url(@cat) %>">New Toy!</a></li>
  <li><a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %>!</a></li>
  <li><a href="<%= cats_url %>">Index</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toys/new.html.erb
<h1><%= @cat.name %>'s New Toy!</h1>

<form action="<%= toys_url %>" method="post">
  <input type="hidden" name="toy[cat_id]" value="<%= @cat.id %>" />

  <label for="toy_name">Name:</label>
  <input type="text" name="toy[name]" id="toy_name" value="<%= @toy.name %>"/>

  <label for="toy_toytype">Toy Type:</label>
  <select name="toy[toytype]" id="toy_toytype">
    <option value="" disabled selected>Select One:</option>
    <option value="string" <%= "selected" if @toy.toytype == "string" %> >
      String
    </option>
    <option value="yarnball" <%= "selected" if @toy.toytype == "yarnball" %> >
      Yarnball
    </option>
    <option value="mouse" <%= "selected" if @toy.toytype == "mouse" %> >
      Mouse
    </option>
  </select>
  <button type="submit">Create Toy!</button>
</form>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>